Fix Copywrite

diff --git a/.github/workflows/hc-copywrite.yml b/.github/workflows/hc-copywrite.yml
--- a/.github/workflows/hc-copywrite.yml
+++ b/.github/workflows/hc-copywrite.yml
@@ -1,4 +1,4 @@
-name: "HashiCorp Copywrite"
+name: "IBM Copywrite"
 
 on:
   schedule:
@@ -19,7 +19,22 @@ jobs:
       uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
 
     - name: Install copywrite
-      uses: hashicorp/setup-copywrite@32638da2d4e81d56a0764aa1547882fc4d209636 # v1.1.3
+      run: make install-copywrite
 
-    - name: Validate Header Compliance
-      run: copywrite headers --plan
+    - name: Generate copywrite headers
+      run: make copywrite
+
+    - name: Validate changes
+      run: git diff --exit-code
+
+    - name: Missing or incorrect headers
+      if: ${{ failure() }}
+      run: |
+        echo "There are files with missing or incorrect copywrite headers. Please run 'make copywrite'."
+        exit 1
+
+    - name: Green light
+      if:   ${{ success() }}
+      run: |
+        echo "All files have correct copywrite headers."
+        exit 0
